network:
    P_fft: 1
    P_ifft: 1
    P_hac: 1
    q_2dfft: 32
    q_2difft: 32
    q_1dfft: 8  # fold this less, won't hurt
    q_1difft: 8 # fold this less, won't hurt
    q_hac: 8
layer:
    T_img_i:
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
    di:
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
    Ni:
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
    fin_pi:
     - 3
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
    fout_pi:
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32
     - 32

