network:
    P_fft: 1
    P_ifft: 1
    P_hac: 1
    q_2dfft: 64
    q_2difft: 64
    q_1dfft: 16  # fold this less, won't hurt
    q_1difft: 16 # fold this less, won't hurt
    q_hac: 16
layer:
    T_img_i:
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
     - 1
    di:
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
     - 15
    Ni:
     - 64
     - 64
     - 64
     - 64
     - 64
     - 64
     - 64
     - 64
     - 64
     - 64
     - 64
     - 64
     - 64
    fin_pi:
     - 3
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
    fout_pi:
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16
     - 16

