algo name: CaP_N_16_full
N avail:
  - 16
d max: 15     # the max batch folding factor that can be supported
layer filter: 
    type: all
range P_hac:
    start: -1
    end: -1
    stride: -1
range T_img:
    start: -1
    end: -1
    stride: -1
range f_in:
    start: -1
    end: -1
    stride: -1
range f_out:
    start: -1
    end: -1
    stride: -1
