network:
    P_fft: 1
    P_ifft: 1
    P_hac: 1
    q_2dfft: 16
    q_2difft: 16
    q_1dfft: 4  # fold this less, won't hurt
    q_1difft: 4 # fold this less, won't hurt
    q_hac: 2
layer:
    fin_pi:
     - 48
     - 64
     - 64
     - 64
    Ni:
     - 16
     - 16
     - 16
     - 16
    fout_pi:
     - 64
     - 64
     - 64
     - 64
    di:
     - 1
     - 1
     - 1
     - 1
    T_img_i:
     - 1
     - 1
     - 1
     - 1

