
name: AlexNet_Limg14
conv_layers:
  - name: conv2
    l_img: 28
    l_kern: 5
    f_in: 96
    f_out: 256
    stride: 1
    pad: 2
  - name: conv3
    l_img: 14
    l_kern: 3
    f_in: 256
    f_out: 384
    stride: 1
    pad: 1
  - name: conv4
    l_img: 14
    l_kern: 3
    f_in: 384
    f_out: 384
    stride: 1
    pad: 1
  - name: conv5
    l_img: 14
    l_kern: 3
    f_in: 384
    f_out: 256
    stride: 1
    pad: 1
